#!/usr/bin/env python3
#
# Copyright (C) 2026 The nasgorOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
# Generates static resource overlays that rename user-visible "LineageOS"
# strings to "NasgorOS" in every locale, without forking any LineageOS app.
#
# Usage: tools/gen-branding-overlay.py <android-source-top>
# Re-run after every LineageOS rebase / Android upgrade and commit the result.

import os
import re
import shutil
import sys

OLD, NEW = "LineageOS", "NasgorOS"

# resource dir (relative to source top) -> string names to rebrand
TARGETS = {
    "lineage-sdk/lineage/res/res": [
        "lineage_version",          # Settings > About phone
        "lineage_updates",
        "lineage_api_level",
        "lineageos_system_label",
    ],
    "packages/apps/SetupWizard/app/src/main/res": [
        "os_name",                  # "Welcome to %s"
        "setup_services",
    ],
    "packages/apps/LineageParts/res": [
        "lineageparts_title",
        "privacy_settings_category",
    ],
}

OVERLAY_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "overlay", "branding")
STRING_RE = re.compile(r'<string\s+name="([^"]+)"[^>]*>.*?</string>', re.DOTALL)
HEADER = ('<?xml version="1.0" encoding="utf-8"?>\n'
          '<!--\n'
          '     Generated by vendor/nasgoros/tools/gen-branding-overlay.py. Do not edit.\n'
          '     SPDX-FileCopyrightText: The nasgorOS Project\n'
          '     SPDX-License-Identifier: Apache-2.0\n'
          '-->\n'
          '<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">\n')


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen-branding-overlay.py <android-source-top>")
    top = sys.argv[1]
    shutil.rmtree(OVERLAY_ROOT, ignore_errors=True)
    total = 0
    for res_dir, names in TARGETS.items():
        src = os.path.join(top, res_dir)
        if not os.path.isdir(src):
            print(f"warning: {res_dir} not found, skipped", file=sys.stderr)
            continue
        found = set()
        for values in sorted(os.listdir(src)):
            path = os.path.join(src, values, "strings.xml")
            if not values.startswith("values") or not os.path.isfile(path):
                continue
            with open(path, encoding="utf-8") as f:
                text = f.read()
            entries = [m.group(0).replace(OLD, NEW) for m in STRING_RE.finditer(text)
                       if m.group(1) in names and OLD in m.group(0)]
            if not entries:
                continue
            found.update(m.group(1) for m in STRING_RE.finditer(text) if m.group(1) in names)
            out = os.path.join(OVERLAY_ROOT, res_dir, values, "strings.xml")
            os.makedirs(os.path.dirname(out), exist_ok=True)
            with open(out, "w", encoding="utf-8") as f:
                f.write(HEADER + "".join(f"    {e}\n" for e in entries) + "</resources>\n")
            total += len(entries)
        missing = sorted(set(names) - found)
        if missing:
            print(f"warning: {res_dir}: string(s) not found: {', '.join(missing)}", file=sys.stderr)
    print(f"generated {total} overlay string(s) in {os.path.relpath(OVERLAY_ROOT)}")


if __name__ == "__main__":
    main()
